### ISSUE TITLE
Payment Gateway Module for WHMCS to integrate with Instamojo.

### ISSUE THREAD

**Issue by thrayam** [kashyapan/WHMCS-Instamojo#1] opened 2016-07-16 15:06 UTC
Hello,

Firstly Thank you for the plugin 

I try to install this plugin in my WHMCS setup, the plugin installation is completed successfully, but the payment is not processing, i setup all required information from instamojo. when i try to make payment, the payment page is is just reloading, it is not directing to payment gateway.

My WHMCS version : 6.3.1

![image](https://cloud.githubusercontent.com/assets/20491785/16895469/efd5b896-4b94-11e6-9b60-666d41871ee2.png)

Please check and let me know what is the issue

Thank you for the support

Thanks
Anu

**Comment by kashyapan** [comment] 2016-07-16 17:52
Open those plugin files in your text editor and make sure that it doesn't have **any white spaces outside php tags**  

php tags will be like this ->
`<?php ?>`

To naked eyes you may not find any white spaces but make sure that they don't exist.  

Hope it helps 

**Edit:**
white spaces were on my source-code I have removed it now.

**Comment by thrayam** [comment] 2016-07-16 19:22
Hi,

Thank you for the update 

I have removed the space & issue still exist

On the viewinvoice.php when i click proceed the page get reloaded ( Also i download the same file you edited)

![image](https://cloud.githubusercontent.com/assets/20491785/16896710/611617da-4bb8-11e6-91fd-850f555093aa.png)

**Comment by thrayam** [comment] 2016-07-16 19:35
Hello,

After one more time code update it is start working

Thank you for the use full plugin

Thanks
Anu

**Comment by thrayam** [comment] 2016-07-16 19:46
Hello,

I would like know one more thing

is it possible to set Payment Gateway Transaction Fee in the plugin.?

Thanks
Anu

**Comment by kashyapan** [comment] 2016-07-17 04:23
Sorry, I don't know much about it.

**Comment by ManoSmriti** [comment] 2016-07-17 07:33
Thanks for this gr8 plugin. Can u plz tell me what is the setting for the return url ? 
Im recieveing the payment in Instamojo , but the Invoice ( in whmcs ) is still Unpaid.

Also, what is the purpose of the two files in the callback folder  and where do i need to upload them ?

Thanx again Buddy.

**Comment by kashyapan** [comment] 2016-07-17 07:41
redirect url is the page where your users will be sent after transactions.
in modules directory there will be a folder called directory. paste both files in there.

callback files are used to update your invoice after payment.

hope that helps

**Comment by ManoSmriti** [comment] 2016-07-17 07:49
Thanx fr the update buddy.

My whmcs is located at : www.example.com/whmcs

#1. So will my redirect url be : example.com/whmcs  ( or any specific file / )

#2. Also, if i understand u correctly, the "callback" folder ( http://example.com/whmcs/modules/gateways/callback ) is the place where the two files need to be placed.

Thank you once again my freind.

**Comment by kashyapan** [comment] 2016-07-17 08:07
Yes exactly.

You're welcome

**Comment by thrayam** [comment] 2016-07-17 09:38
Hi,

i tried to use callback like below and ll it is redirecting to home page, invoice still pending, also i tried use file name in the callback url like http://example.com/modules/gateways/callback/instamojo.php, when i use like this it showing blank page, in url it is showing payment_id & payment_request_id

Could you please look this 

![image](https://cloud.githubusercontent.com/assets/20491785/16899835/21428fb8-4c2f-11e6-8978-2e6db887bd6f.png)

**Comment by ManoSmriti** [comment] 2016-07-17 09:41
The Invoice is Not getting Marked as paid. I guess its the same issue as reported by @thrayam

**Comment by thrayam** [comment] 2016-07-17 10:03
Yes @ManoSmriti the invoice is not marked paid

**Comment by kashyapan** [comment] 2016-07-17 10:16
I was using test version of instamojo . So if the problem is due to that following code should  fix the problem.

[imojo-1.txt](https://github.com/kashyapan/WHMCS-Instamojo/files/367769/imojo-1.txt)

paste it in callback/instamojo.php

Make sure that you have pasted both files in callback folder. 

 I too had that problem but it was because sometimes I pasted same files in both folders. (Even-though there are two files named instamojo.php they are different).

Let me know if the problem resist

**Comment by thrayam** [comment] 2016-07-17 10:21
@kashyapan, thank you for the quick update, will check and update you soon

Could you please confirm the callback url in the admin side

http://example.com/modules/gateways/callback
or
http://example.com/modules/gateways/callback/instamojo.php

Thanks
Anu

**Comment by kashyapan** [comment] 2016-07-17 10:29
http://example.com/modules/gateways/callback/instamojo.php -> This is callback file
http://example.com/modules/gateways/callback/                        -> This is folder in which instamojo.php & instamojo_class.php is to be pasted

**Comment by thrayam** [comment] 2016-07-17 10:31
Ok, these files already in the folder, i mean url in admin side Redirect URL

![image](https://cloud.githubusercontent.com/assets/20491785/16899835/21428fb8-4c2f-11e6-8978-2e6db887bd6f.png)

which url should be here .?

**Comment by thrayam** [comment] 2016-07-17 10:37
I tried both url

http://example.com/modules/gateways/callback/instamojo.php 
&
http://example.com/modules/gateways/callback/ 

both are not working, 

When i use first url after payment is showing 

![image](https://cloud.githubusercontent.com/assets/20491785/16900107/75a5d2d2-4c38-11e6-9182-fe3754a238c2.png)

and second url redirecting to home page

After both payment invoice still unpaid 

Thanks
Anu

**Comment by kashyapan** [comment] 2016-07-17 11:28
There is no need to visit those URLs . 
Visit the below link
https://www.instamojo.com/webhook-testing-tool/

You will find couple of options there
Select your transaction there

Make your server URL as 
http://example.com/modules/gateways/callback/instamojo.php 

Now click SEND webhook.

After you do that check your WHMCS. The paid status must have changed.

**Comment by thrayam** [comment] 2016-07-17 11:47
Hi,

I tried this &  getting Response 500 and still in the status in WHMCS is in unpaid

![image](https://cloud.githubusercontent.com/assets/20491785/16900433/2f0f6cd4-4c42-11e6-89c7-2221c75200b2.png)

![image](https://cloud.githubusercontent.com/assets/20491785/16900435/43329efc-4c42-11e6-99e8-d19714998e6c.png)

![image](https://cloud.githubusercontent.com/assets/20491785/16900480/3e0a9b90-4c43-11e6-83de-5fce05e14493.png)

**Comment by kashyapan** [comment] 2016-07-17 16:56
In callback/instamojo.php paste following on top

```
error_reporting(E_ALL);
ini_set('display_errors', 'On');
```

Instead of error 500 you will be displayed with specific error Share that screenshot.

**Comment by thrayam** [comment] 2016-07-17 17:10
@kashyapan 

Here is the screen shot

![image](https://cloud.githubusercontent.com/assets/20491785/16901973/81ea8c40-4c6f-11e6-8335-b1f7848778b0.png)

**Comment by thrayam** [comment] 2016-07-17 17:13
From error_log

[17-Jul-2016 17:10:14 Etc/GMT] PHP Warning:  include(../../../dbconnect.php): failed to open stream: No such file or directory in /home/thrayet2/public_html/client/modules/gateways/callback/instamojo.php on line 44
[17-Jul-2016 17:10:14 Etc/GMT] PHP Warning:  include(../../../dbconnect.php): failed to open stream: No such file or directory in /home/thrayet2/public_html/client/modules/gateways/callback/instamojo.php on line 44
[17-Jul-2016 17:10:14 Etc/GMT] PHP Warning:  include(): Failed opening '../../../dbconnect.php' for inclusion (include_path='.:/opt/alt/php56/usr/share/pear:/opt/alt/php56/usr/share/php') in /home/thrayet2/public_html/client/modules/gateways/callback/instamojo.php on line 44
[17-Jul-2016 17:10:14 Etc/GMT] PHP Fatal error:  Class 'WHMCS\Invoice' not found in /home/thrayet2/public_html/client/includes/gatewayfunctions.php on line 0

Looks like file path is not correct

**Comment by thrayam** [comment] 2016-07-17 17:19
@kashyapan i go through my files and i'm unable to find file called dbconnect.php

I can find all other files

include("../../../includes/functions.php");
include("../../../includes/gatewayfunctions.php");
include("../../../includes/invoicefunctions.php");

**Comment by kashyapan** [comment] 2016-07-17 17:32
It should be in root directory.  

for you it must be in "client" folder.

**Comment by kashyapan** [comment] 2016-07-17 17:38
It should be in root directory.  

for you it must be in "client" folder.

**Comment by thrayam** [comment] 2016-07-17 17:40
@kashyapan 

There is no such a files available, please see the screen shot

![image](https://cloud.githubusercontent.com/assets/20491785/16902128/19d643c0-4c73-11e6-9ece-b4a1668c5440.png)

From WHMCS 6.0 they have removed dbconnect, i'm using WHMCS 6.3.1

Please check the below url

http://docs.whmcs.com/Version_6.0_Release_Notes#Removal_of_Dbconnect.php

**Comment by thrayam** [comment] 2016-07-17 17:43
@kashyapan , As per the WHMCS documentation i just used include("../../../init.php");

I gor Response : 200, with out any error message,  but still the invoice is unpaid :cry: 

![image](https://cloud.githubusercontent.com/assets/20491785/16902151/ed5fcf4a-4c73-11e6-9b72-c86220c38eef.png)

**Comment by kashyapan** [comment] 2016-07-17 17:46
@thrayam I was using an older version. Probably Something significant has changed in Version 6.

**Comment by thrayam** [comment] 2016-07-17 18:14
Hi @kashyapan,

May be below link will help you update the functions, i dont think it will be big changes, it should be some minor changes :high_brightness: :smiley: 

https://github.com/WHMCS/sample-gateway-module

http://docs.whmcs.com/Creating_Modules

Thanks
Anu

**Comment by big89** [comment] 2016-08-29 11:13
Hello All,

If any one wants to discuss on this, contact me. I will help regarding this development.

**Comment by big89** [comment] 2016-09-15 10:48
Hello All,

If any one wants to discuss on this, contact me. I will help regarding this development.

**Closed as completed** 2017-06-23 06:33 UTC
